### ISSUE TITLE
onWindowChangedが毎フレーム発生してしまう

### ISSUE THREAD

**Issue by gtk2k** [hecomi/uWindowCapture#10]
uWindowCaptureバージョン 0.5.0

お世話になります。
uWindowCaptureのUwcWindowCaptureをAddComponent()及びonWindowChangedをAddListenerすると、onWindowChangedイベントが毎フレーム発生してしまいます。
desktopIndexプロパティの更新などを行うと毎フレームの発生は止まります。
できれば、AddCmponent()直後においても毎フレームのイベントが発生しないようにしていただければと思います。

よろしくお願いします。

再現プロジェクト
https://drive.google.com/file/d/1iYfgUPHH2U4zX-w3FyN_X939RqqOuHJH/view?usp=sharing

**Comment by hecomi** [comment]
ご報告ありがとうございます。
こちら対応しましたので、最新のコミットまたは下記ファイルからご確認ください。
[uWindowCapture-v0.5.1.zip](https://github.com/hecomi/uWindowCapture/files/2850689/uWindowCapture-v0.5.1.zip)

**Comment by gtk2k** [comment]
対応ありがとうございます。
