### ISSUE TITLE
onWindowChangedイベントでwindow.widthやwindow.heightなどが変更前の値になる

### ISSUE THREAD

**Issue by gtk2k** [hecomi/uWindowCapture#11]
uWindowCaptureバージョン 0.5.0

お世話になります。
WindowChangedイベントで、window.width/window.height等のプロパティを参照すると、イベント名過去形のイベントですので変更後のモニターのサイズが取得されるのが期待する動作だと思いますが、
変更前のモニターのサイズ(type = WindowTextureType.Desktopにしています)が取得されてしまいます。
変更後のモニターのサイズが取得されるように修正を希望します。

よろしくお願いします。

再現プロジェクト
https://drive.google.com/file/d/1iYfgUPHH2U4zX-w3FyN_X939RqqOuHJH/view?usp=sharing

**Comment by hecomi** [comment]
`onWindowChanged` イベントはあくまで `UwcWindowTexture` の `window` プロパティが変更されたことに関する通知になりますので、`UwcWindow` の `onSizeChanged` イベントハンドラをご使用ください。

```cs
using UnityEngine;
using uWindowCapture;

public class Test : MonoBehaviour
{
    UwcWindowTexture tex;

    void Start()
    {
        tex = gameObject.AddComponent<UwcWindowTexture>();
        tex.desktopIndex = 0;
        tex.type = WindowTextureType.Desktop;

        tex.onWindowChanged.AddListener((w, ow) =>
        {
            Debug.Log("onWindowChanged");

            // このタイミングはウィンドウがセットされただけ
            Debug.Log(string.Format("width: {0}, height: {1}", w.width, w.height));

            // このタイミングでキャプチャ & ウィンドウサイズが取得された
            w.onSizeChanged.AddListener(() => {
                Debug.Log(string.Format("width: {0}, height: {1}", w.width, w.height));
            });
        });
    }
}
```

`window` プロパティの変更だけではキャプチャはされず、あくまでセットした後に更新フラグが立ち、非同期でキャプチャが行われ、キャプチャが完了した場合に `onCaptured`、そのテクスチャサイズが変更されていた（または初回キャプチャな）ら `onSizeChanged` がコールされます。

**Comment by gtk2k** [comment]
解説ありがとうございます。
了解しました。

**Comment by gtk2k** [comment]
クローズした後で申し訳ございませんが、一応、初回はonSizeChangedが発火し期待する動作となりましたが、しかし、２回目以降がイベントが発火されませんでした。
”２回目”とは、現在、desktopIndexプロパティに値をセットすることで切り替えているのですが、この切り替えのことを指します。

**Comment by hecomi** [comment]
返信遅くなってしまい申し訳ありません。

`onSizeChanged` はキャプチャ対象のテクスチャのサイズが変化したことを意味しているので、単に `desktopIndex` を切り替えただけでは発火しません（`UwcWindowTexture` は単に `UwcWindow` が保持しているテクスチャを参照するだけで、`UwcWindow` は `UwcWindowTexture` とは関係なく `UwcManager` によって管理されているため）。仕様がちょっとわかりにくいですが、サイズが変更された瞬間だけ取りたい場合は次のようにして見てください。

**Test.cs**
```cs
using UnityEngine;
using uWindowCapture;

public class Test : MonoBehaviour
{
    UwcWindowTexture tex;

    [SerializeField]
    int desktopIndex = 0;

    void Start()
    {
        tex = gameObject.AddComponent<UwcWindowTexture>();
        tex.desktopIndex = 0;
        tex.type = WindowTextureType.Desktop;

        tex.onWindowChanged.AddListener((w, ow) =>
        {
            Debug.Log("onWindowChanged");

            if (w.width != 0 && w.height != 0)
            {
                // ２回目以降はサイズが取れる
                Debug.Log(string.Format("2. width: {0}, height: {1}", w.width, w.height));
            }
            else
            {
                // このタイミングは初回はウィンドウがセットされただけ
                Debug.Log(string.Format("0. width: {0}, height: {1}", w.width, w.height));

                // このタイミングでキャプチャ & ウィンドウサイズが取得された
                w.onSizeChanged.AddListener(OnSizeChanged);
            }
        });
    }

    void Update()
    {
        tex.desktopIndex = desktopIndex;
    }

    void OnSizeChanged()
    {
        Debug.Log("onSizeChanged");
        var w = tex.window;
        Debug.Log(string.Format("1. width: {0}, height: {1}", w.width, w.height));
        w.onSizeChanged.RemoveListener(OnSizeChanged);
    }
}
```
**出力：**
<img width="580" alt="output" src="https://user-images.githubusercontent.com/493433/52894700-cac07280-31f1-11e9-9de9-65a6cf2db175.PNG">

（初回の `onWindowChanged` は `AddComponent` 時、以降はインスペクタから `desktopIndex` を変更した場合（0 -> 1 -> 0 -> 1））

**Comment by gtk2k** [comment]
ありがとうございます。
了解しました。
