### ISSUE TITLE
Some windows block the window capture from changing

### ISSUE THREAD

**Issue by CurtisVL** [hecomi/uWindowCapture#12]
It seems that some windows (Such as Spotify for Windows 10) will block the window capture from changing to another window. (Changing the window title variable)

Maybe this is an issue with all UWP apps? I didn't test others yet. :)

**Comment by hecomi** [comment]
Thank you for giving a good hint to imorove uWC. I'll check the problem asap.

**Comment by hecomi** [comment]
Sorry for my late work. I've checked this bug recently and fix the blocking bug caused in my environment when using Spotify. Could you check the latest version in your environment?
https://github.com/hecomi/uWindowCapture/releases/tag/v0.6.0
