### ISSUE TITLE
DPI scaling issue when moving window between 2 monitors with separate scaling

### ISSUE THREAD

**Issue by CurtisVL** [hecomi/uWindowCapture#13]
There is a DPI scaling issue when moving window between 2 monitors with separate scaling.
To reproduce:
Start capturing a window on one monitor, then, move the window to a monitor with different scaling. (150% to 100% in my testing)

Example:
https://i.gyazo.com/ab4c4529bd14c3428a4b74c2d3290f72.png

hope this helps! :)

**Comment by Matt2468rv** [comment]
Can also confirm this same issue.

**Comment by hecomi** [comment]
Thank you for the report. I've fixed it in the lateset version:
https://github.com/hecomi/uWindowCapture/releases/tag/v0.6.0
