### ISSUE TITLE
(Feature suggestion) Multi-core window capture

### ISSUE THREAD

**Issue by CurtisVL** [hecomi/uWindowCapture#14]
Hi there!

Is it possible to capture windows async?
I researched it myself briefly but wasn't sure if PrintWindow could be used async.

If so, this would be an amazing additional as generally capturing just one window at 30 FPS can be enough to max out a single core on a lot of CPUs.

Thanks! :)

**Comment by hecomi** [comment]
Thank you for the suggestion.

But it seems impossible to use capture functions asynchronously. At the beginning phase of the development, I implemented async capture but the performance wasn't improved...

**Comment by CurtisVL** [comment]
Thanks for your fast response on this!
I wasn't sure it would be possible but I wanted to ask to check! :)
