### ISSUE TITLE
Mouse cursor capture only updates position if cursor is on the main display

### ISSUE THREAD

**Issue by Xiexe** [hecomi/uWindowCapture#15]
I.E. You have two monitor captures, you can see the mouse cursor just fine on the main display, however, the secondary display will not show the cursor if it is on it, and will instead show a mirror of the cursor on the primary display.

**Comment by hecomi** [comment]
Thank you for the report. I've fixed it in v0.6.0:
https://github.com/hecomi/uWindowCapture/releases/tag/v0.6.0
