### ISSUE TITLE
Recent windows update (KB4541335) causes some windows to flicker.

### ISSUE THREAD

**Issue by Curtis-VL** [hecomi/uWindowCapture#22]
Recent windows update (KB4541335) causes some windows to flicker. The flickering briefly causes the Windows 7 style 'Aero' border to appear on windows. I believe this is a Windows bug as it has only started with that specific update.

A friend of mine said it's caused by the window re-drawing when being captured too frequently, however, this same issue is happening with the capture framerate set to 30 FPS.

Can reproduce using Spotify's desktop app, or I believe Steam.

**Comment by oddruud** [comment]
I have this same issue. @Curtis-VL did you find a solution for this?

**Comment by oddruud** [comment]
Thanks Curtis! 👍

**Comment by Curtis-VL** [comment]
I'll close this issue as the issue was resolved by Windows 10 version 2004 and later. The fix is simply to update Windows. :)
