### ISSUE TITLE
linker errors when building with IL2CPP

### ISSUE THREAD

**Issue by oddruud** [hecomi/uWindowCapture#24]
Good day! I am trying to build the uwindowcapture plugin with IL2CPP but im getting the following error when building: 

Msvc Install Version: 15.0
	Msvc Install SDK Directory: C:\Program Files (x86)\Windows Kits\10
	Msvc Linker Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe
	Msvc Compiler Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe

il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException: WindowTexture.cpp
<my project directory>\Temp\StagingArea\Data\il2cppOutput\WindowTexture.cpp(172): error C3861: 'max': identifier not found
..along with errors for other references to the max function.  

is this caused by assembly stripping? what could I do to fix this?

**Comment by oddruud** [comment]
nevermind!  i did something silly

**Comment by LimeBlossom** [comment]
I just ran into this, do you happen to remember what you did?
