### ISSUE TITLE
Resizing a captured window causes black window in Unity (WGC)

### ISSUE THREAD

**Issue by Curtis-VL** [hecomi/uWindowCapture#27]
Resizing a captured window causes black window in Unity when using Windows.Graphics.Capture.

**Comment by Curtis-VL** [comment]
To clarify, the Texture2D appears to be correct, but within Unity's 'Game' view the window becomes black. :)

**Comment by hecomi** [comment]
Was the version that you used v1.0.1 or v1.0.0?

**Comment by Curtis-VL** [comment]
Tested now with v1.0.1 and can still reproduce the issue.

Here a video demonstrating the issue:
https://gyazo.com/d0e399ccaab525560d4133e0f029e05f

**Comment by hecomi** [comment]
I was able to reproduce the bug and will fix it as soon as possible.

**Comment by Curtis-VL** [comment]
Confirmed fixed, thank you!
