### ISSUE TITLE
Voicemeter Potato can't be captured with Windows.Graphics.Capture

### ISSUE THREAD

**Issue by Curtis-VL** [hecomi/uWindowCapture#29]
Voicemeter Potato can't be captured with Windows.Graphics.Capture, latest version v3.0.1.8. (32 or 64-bit version)

The window shows a white texture, cursor input is inverted. Top is bottom.

Works as intended with PrintWindow, and, Voicemeter is able to be captured by OBS using their Windows.Graphics.Capture method.

**Comment by hecomi** [comment]
Hi, I've just released v1.0.2 which includes this bug fix!
- https://github.com/hecomi/uWindowCapture/releases/tag/v1.0.2

**Comment by Curtis-VL** [comment]
Can confirm this issue is fixed, thanks!
