### ISSUE TITLE
unity2020 and win8

### ISSUE THREAD

**Issue by moocowmoomoo** [hecomi/uWindowCapture#31]
Hi @hecomi, I'm getting errors about not being able to load the .dll - is this because I need a newer version of windows than win8?

**Comment by hecomi** [comment]
The latest uWindowCapture uses an API called Windows Graphics Capture, which was implemented in Windows 10 April 2018 Update (1803). For this reason, it is currently not available for the older versions of Windows. Please use the older version, v0.6.0, instead.

- https://github.com/hecomi/uWindowCapture/releases/tag/v0.6.0

In the future, this problem may be solved by supporting "delayload", but it is still technically a long way off...

**Comment by moocowmoomoo** [comment]
ok hecomi, thanks for the help!
