### ISSUE TITLE
VR support

### ISSUE THREAD

**Issue by supneo** [hecomi/uWindowCapture#38]
Hello , it would be nice to support the oculus and steam vr

**Comment by hecomi** [comment]
This project is also used in the VR apps such as OVR Toolkit and works fine in VR.

**Comment by LimeBlossom** [comment]
For anyone else that found this after trying to fix the Window only showing in one eye, try setting Render Mode to Multi Pass.

**Comment by Lee-daeho** [comment]
@LimeBlossom You saved me. Thanks!
