### ISSUE TITLE
'uWindowCapture' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by jasonhbartlett** [hecomi/uWindowCapture#41]
Hello, I added uWindowCapture package via UPM git url.  I'm wanting to reference the classes from the uWindowCapture namespace in my own scripts but after adding the #using uWindowCapture; I'm getting the following error:

error CS0246: The type or namespace name 'uWindowCapture' could not be found (are you missing a using directive or an assembly reference?)

**Comment by jasonhbartlett** [comment]
I don't know if perhaps this is due to duplicate assembly names where the plugins are named uWindowCapture and the ASDF file in Runtime folder is also named uWindowCapture.

I notice in the uDesktopDuplication package, you have named the ASDF in the runtime folder uDesktopDuplication.Runtime

Perhaps renaming the ASDF to uWindowCapture.Runtime will fix it, but I cannot do that as it's part of the package.

**Comment by jasonhbartlett** [comment]
@hecomi Can you confirm this issue isn't something on my end? I will take suggestions if you have any.

**Comment by jasonhbartlett** [comment]
Hi @hecomi ,
Doing that by itself doesn't seem to work.  But by also changing the uWindowCapture.asmdef "autoReferenced"**:true**,  and then Re-importing it - Then it DOES work.

Same for the Samples.  I have to set Auto Referenced to **True** and re-import, then I am able to reference the public methods.

Did you not want the asmdef file for uWindowCapture to be auto referenced?  I notice uDesktopDuplication asmdef file has auto referenced set to True.  I had no problem with that package regarding the references.  What is the difference between the 2 packages regarding references?

**Comment by hecomi** [comment]
Thanks for the report, it is a mistake that `Auto Referenced` is false. I'll check it when I have time on the weekend.

**Comment by hecomi** [comment]
This problem was fixed in v1.1.2:
- https://github.com/hecomi/uWindowCapture/commit/018442768ca2083d420dd60111483ba80715dc38#diff-06077fe4c1b626e730b69324b7fb9b24a6b6e528eaf9e3cfaacab627724bdb65
Thank you very much again!
