### ISSUE TITLE
bad performance with window.GetPixels

### ISSUE THREAD

**Issue by BonnyShen** [hecomi/uWindowCapture#42]
Hello, I want to get the rawdata of  the texture. So I use Texture2D.GetRawTextureData which give me an empty texture. I searched and found maybe dx and opengl makes it impossible to get the right rawdata. 
So I use window.GetPixels and copy the Color32[] to a new Texture and it worked. But when I use window.GetPixels the fps was changed to 15 from 60.
I want to know if I have a better way to do this , or an enchancement to the function

![shortcut_191520](https://user-images.githubusercontent.com/1468447/144836926-9c94de87-edf9-4dbd-a3aa-fae65ca4d0c1.png)
?

**Comment by hecomi** [comment]
Yes, `GetPixels()`, which allocates a huge array in C#'s managed area, is a very heavy process. This is the same situation as `UnityEngine.Texture2D.GetPixels()`'s one. Unfortunately, there is no way to speed it up. but it is possible to prevent the frame rate drop by processing it in a thread or job.

**Comment by BonnyShen** [comment]
Thank you for you replay. Thread is worked for me.
