### ISSUE TITLE
LNK1104 for uWindowCapture.def

### ISSUE THREAD

**Issue by brunoatvenosa** [hecomi/uWindowCapture#45]
I believe this is me not knowing how to properly configure my project, but I am receiving this error when trying to compile from main branch. Can anyone help me?

Project path doesn't contain spaces.
uWindowCapture.def is on uWindowsCapture project root structure.

**Comment by brunoatvenosa** [comment]
Drag and drop to visual studio creates a symbolic link, which was not resolving correctly. Copying the actual file solved the problem.

**Comment by ysyyork** [comment]
just wondering, why not just place this file under the project folder in this case?
