### ISSUE TITLE
About screen share

### ISSUE THREAD

**Issue by steven060594** [hecomi/uWindowCapture#46]
Hello, I know this is an asset to capture windows, but is it possible for sharing live screen networks?

thanks.

**Comment by hecomi** [comment]
This can be done by encoding the texture, sending it to a remote PC using some video transmission protocol, and decoding it. This is an example that encodes/decodes the texture using NVIDIA's NvEncoder / NvDecoder API and sending it using a simple UDP method.
- https://github.com/hecomi/UnityRemoteDesktopDuplication
