### ISSUE TITLE
(Feature suggestion) Ability to flip texture

### ISSUE THREAD

**Issue by CurtisVL** [hecomi/uWindowCapture#6]
Hi,

I'm using this asset to display a window capture texture onto a SteamVR Overlay, however, the texture is flipped and as far as I'm aware there's no way to flip it back.

Is it possible to implement an option to flip the texture itself? I'm well aware this could be done through a material within Unity, but in my case the texture is going directly into a SteamVR Overlay, so no material options are available.

Loving the asset so far though, good job. :)

**Comment by hecomi** [comment]
Thanks for using my asset and giving the feedback!

I'll make 2 options in the future.
1. add an unlit shader which has a shader property to flip the texture (faster).
2. add a serialized field in `UwcWindowCapture` to flip the texture for the case of using different shader from above (slower)

Please wait for the next update ;)

**Comment by hecomi** [comment]
I released [v0.3.0](https://github.com/hecomi/uWindowCapture/releases/tag/v0.3.0) just a few minutes ago. This version has shaders that has properties to flip the captured texture (the 1. option in the above post). Regarding the 2., I had a significant performance issue, so now I didn't include it in this release.

**Comment by CurtisVL** [comment]
Thanks for the update!
I just wanted to check if you think the 2. would be possible at some point? If it's too much of a performance hit that can't be resolved, that's perfectly fine.
I'd just like to know so I can work around it if required. 👍

**Comment by CurtisVL** [comment]
Going to close this issue as I feel it's not possible without too large of a performance hit! Personally, I work around this issue in my own way anyway! :)
